# Generated by Django 2.2 on 2020-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(db_index=True, editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
